### ISSUE TITLE
README.md requires contributors.

### ISSUE THREAD

**Issue by Kgomotso196** [kalbek/Portfolio#4]
Kindly consider adding contributors to your README.md.

**Comment by kalbek** [comment]
I agree, at first, the project had no contribution, but now that 4 or 5 people have collaborated on this repo I will consider mentioning their names on the readme file.

**Comment by BANCUNGUYE66** [comment]
Great work! I liked the way your code is structured 👏🏾

**Comment by yin-ka** [comment]
> Kindly consider adding contributors on your README.md.

I agree, doing such acknowledges their contributions to the project.
