### ISSUE TITLE
Suggestions : Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by ehmaddd** [kalbek/Portfolio#8]
The peers reviewed the code thoroughly and found it well-organized according to the microverse README templates guideline. The only one thing found was broken the Live Demo Link in the README file, which was to be added to make the website accessible with 1-click.

**Comment by kalbek** [comment]
I totally agree on this issue. The project needs a link for the live demo section.

**Comment by touredri** [comment]
Good job
